name: dsm_helper
description: 适用于群辉6.x的手机助手。采用新拟态设计风格

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.86+86

environment:
  sdk: ">=2.10.0 <3.0.0"

dependency_overrides:
  http: ^0.13.1
  video_player: ^2.1.1
  html: ^0.15.0
  csslib: ^0.17.0
  convert: ^3.0.0
  quiver: ^3.0.1
  chewie_audio: ^1.2.0
  flutter_svg: ^0.22.0
  chewie: ^1.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
#  fluttertoast: ^7.1.6
  oktoast: ^3.0.0
  package_info: ^2.0.0
  pull_to_refresh: ^1.6.5
  shared_preferences: ^2.0.5
  permission_handler: ^7.0.0
  extended_image: ^4.0.1
  cool_ui: ^1.0.2
  gallery_saver: ^2.1.0
  android_intent: ^2.0.0
  path_provider: ^2.0.1
  flutter_downloader: ^1.6.0
  percent_indicator: ^3.0.1
  fl_chart: ^0.35.0
  flutter_animation_progress_bar: ^2.0.0
  file_picker: ^3.0.1
  open_file: ^3.2.0
  flutter_datetime_picker: ^1.5.1
  flutter_swiper: ^1.1.6
  flutter_swiper_null_safety: ^1.0.1
  html: ^0.15.0
  flutter_html: ^1.3.0
  provider: ^5.0.0
  wave: ^0.2.0
  dartssh: ^1.0.3+3
  xterm: ^2.0.0
  umeng_analytics_plugin: ^1.0.3
  photo_manager: ^1.1.4
  vibrate: ^0.0.4
  url_launcher: ^6.0.3
  http: ^0.13.1
  local_auth: ^1.1.5
  gesture_password: ^0.0.6
  connectivity: ^3.0.3
  code_editor: ^1.1.1
  flutter_highlight: ^0.7.0
  syncfusion_flutter_pdfviewer: ^19.1.58-beta
  wechat_assets_picker: ^5.1.3
  dio: ^4.0.0
  draggable_scrollbar:
    git: https://gitee.com/challengerV/draggable_scrollbar.git

#  dio:
#    git: https://gitee.com/challengerV/dio.git
  neumorphic:
    git: https://gitee.com/challengerV/neumorphic.git
  receive_sharing_intent:
    git: https://gitee.com/challengerV/receive_sharing_intent.git
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/tabbar/
    - assets/icons/
    - assets/applications/
    - assets/applications/6/
    - assets/applications/7/
    - assets/control_panel/
    - assets/control_panel/6/
    - assets/control_panel/7/
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
